version: "3"
services:
  react-app:
    image: frontend
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes: 
      - ./projfrontend/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: backend
    ports:
      - "8000:8000"
    networks:
      - mern-app
    volumes: 
      - ./projbackend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local